### ISSUE TITLE
Decide/Prototype world implementation approach

### ISSUE THREAD

**Issue by cptn-solo** [cptn-solo/xplora#27]

**Comment by Arteg0r** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Карта мира, первая итерация](https://trello.com/c/Wul6dWy4/24-%D0%BA%D0%B0%D1%80%D1%82%D0%B0-%D0%BC%D0%B8%D1%80%D0%B0-%D0%BF%D0%B5%D1%80%D0%B2%D0%B0%D1%8F-%D0%B8%D1%82%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D1%8F)
