### ISSUE TITLE
событие на экономию выносливости: revisit

### ISSUE THREAD

**Issue by cptn-solo** [cptn-solo/xplora#74]
работает сразу, длительность 3 хода, работает и после боя, есть бой был в течение этих 3 ходов, но сам бой отнимает 10 очков, пока работает - барчик выносливости "леденеет"

**Comment by Arteg0r** [comment]
+ изменить названия бонусов на кнопке https://docs.google.com/spreadsheets/d/12acMQ8UTlDRHP0NvzSGVLYKb9QMhw2AjD9EKXTQug3U/edit#gid=1297383192&range=G19
